# Generated by Django 2.2 on 2020-03-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('ccode', models.CharField(max_length=30)),
                ('crank', models.IntegerField()),
            ],
        ),
    ]
